In [1]:
## Proptech

In [28]:
# Import the required libraries and dependencies
import pandas as pd
import hvplot.pandas
from pathlib import Path

In [29]:
## Import the Data from the resources folder

In [30]:
# Using the read_csv function and Path module, create a DataFrame 
# by importing the sfo_neighborhoods_census_data.csv file from the Resources folder
sfo_data_df = pd.read_csv(Path('./Resources/sfo_neighborhoods_census_data.csv'))

# Review the first and last five rows of the DataFrame
display(sfo_data_df.head())
sfo_data_df.tail()

   year      neighborhood  sale_price_sqr_foot  housing_units  gross_rent
0  2010      Alamo Square           291.182945         372560        1239
1  2010        Anza Vista           267.932583         372560        1239
2  2010           Bayview           170.098665         372560        1239
3  2010  Buena Vista Park           347.394919         372560        1239
4  2010  Central Richmond           319.027623         372560        1239

,year,neighborhood,sale_price_sqr_foot,housing_units,gross_rent
392,2016,Telegraph Hill,903.049771,384242,4390
393,2016,Twin Peaks,970.085470,384242,4390
394,2016,Van Ness/ Civic Center,552.602567,384242,4390
395,2016,Visitacion Valley,328.319007,384242,4390
396,2016,Westwood Park,631.195426,384242,4390

In [31]:
## Calculate and Plot the Housing Units per Year

In [32]:
# Sort out the housing units by year
housing_units_by_year = (sfo_data_df[['year','housing_units']])

# Review the DataFrame
display(housing_units_by_year)

     year  housing_units
0    2010         372560
1    2010         372560
2    2010         372560
3    2010         372560
4    2010         372560
..    ...            ...
392  2016         384242
393  2016         384242
394  2016         384242
395  2016         384242
396  2016         384242

[397 rows x 2 columns]

In [33]:
# Use groupby and mean to create a numerical aggregation that groups data by the year then averages the results
avg_housing_units_by_year=housing_units_by_year.groupby('year').mean()
display(avg_housing_units_by_year)

      housing_units
year
2010         372560
2011         374507
2012         376454
2013         378401
2014         380348
2015         382295
2016         384242

In [34]:
# Create a visual aggregation explore the housing units by year using hvplot
avg_housing_units_by_year.hvplot(kind='bar',title='Average Housing Units Available by Year', ylim=(350000,390000)).opts(yformatter='%.0f')

:Bars   [year]   (housing_units)

In [35]:
## Calculate and Plot the Average Sale Prices per Square Foot

In [36]:
# Sort out sale_price_sqr_foot and gross_rent by year
prices_square_foot_by_year = (sfo_data_df[['year','sale_price_sqr_foot','gross_rent']])

# Review the resulting DataFrame
prices_square_foot_by_year

     year  sale_price_sqr_foot  gross_rent
0    2010           291.182945        1239
1    2010           267.932583        1239
2    2010           170.098665        1239
3    2010           347.394919        1239
4    2010           319.027623        1239
..    ...                  ...         ...
392  2016           903.049771        4390
393  2016           970.085470        4390
394  2016           552.602567        4390
395  2016           328.319007        4390
396  2016           631.195426        4390

[397 rows x 3 columns]

In [37]:
# Use groupby and mean to create a numerical aggregation that groups data by the year then averages the results
avg_prices_square_foot_by_year=(prices_square_foot_by_year.groupby('year').mean())
display(avg_prices_square_foot_by_year)

      sale_price_sqr_foot  gross_rent
year
2010           369.344353        1239
2011           341.903429        1530
2012           399.389968        2324
2013           483.600304        2971
2014           556.277273        3528
2015           632.540352        3739
2016           697.643709        4390

In [38]:
# Plot prices_square_foot_by_year. 
avg_prices_square_foot_by_year.hvplot(title='Compare the Avg Price to Buy vs Avg Gross Rent')

:NdOverlay   [Variable]
   :Curve   [year]   (value)

In [39]:
## Compare the Average Sales Price by neighborhood

In [40]:
# Sort by year and neighborhood and price
prices_by_year_by_neighborhood = (sfo_data_df[['year','neighborhood','sale_price_sqr_foot','gross_rent']])

# Review the DataFrame
prices_by_year_by_neighborhood.set_index('year')

                neighborhood  sale_price_sqr_foot  gross_rent
year
2010            Alamo Square           291.182945        1239
2010              Anza Vista           267.932583        1239
2010                 Bayview           170.098665        1239
2010        Buena Vista Park           347.394919        1239
2010        Central Richmond           319.027623        1239
...                      ...                  ...         ...
2016          Telegraph Hill           903.049771        4390
2016              Twin Peaks           970.085470        4390
2016  Van Ness/ Civic Center           552.602567        4390
2016       Visitacion Valley           328.319007        4390
2016           Westwood Park           631.195426        4390

[397 rows x 3 columns]

In [41]:
# Create a new dataframe grouping the data by year and neighborhood then show the average price
test=(prices_by_year_by_neighborhood.groupby('year').mean())
test.head(25)

      sale_price_sqr_foot  gross_rent
year
2010           369.344353        1239
2011           341.903429        1530
2012           399.389968        2324
2013           483.600304        2971
2014           556.277273        3528
2015           632.540352        3739
2016           697.643709        4390

In [42]:
test=test.pct_change()
display(test)

      sale_price_sqr_foot  gross_rent
year
2010                  NaN         NaN
2011            -0.074296    0.234867
2012             0.168137    0.518954
2013             0.210847    0.278399
2014             0.150283    0.187479
2015             0.137095    0.059807
2016             0.102924    0.174111

In [43]:
test.hvplot.line()

:NdOverlay   [Variable]
   :Curve   [year]   (value)

In [44]:
# Filter out the housing_units
prices_by_year_by_neighborhood = sfo_data_df.drop(columns=['housing_units'])

# Review the DataFrame
prices_by_year_by_neighborhood

     year            neighborhood  sale_price_sqr_foot  gross_rent
0    2010            Alamo Square           291.182945        1239
1    2010              Anza Vista           267.932583        1239
2    2010                 Bayview           170.098665        1239
3    2010        Buena Vista Park           347.394919        1239
4    2010        Central Richmond           319.027623        1239
..    ...                     ...                  ...         ...
392  2016          Telegraph Hill           903.049771        4390
393  2016              Twin Peaks           970.085470        4390
394  2016  Van Ness/ Civic Center           552.602567        4390
395  2016       Visitacion Valley           328.319007        4390
396  2016           Westwood Park           631.195426        4390

[397 rows x 4 columns]

In [45]:
# Group by neighborhood and by year, then show the prices
prices_by_year_by_neighborhood.set_index(['year','neighborhood'])

                             sale_price_sqr_foot  gross_rent
year neighborhood
2010 Alamo Square                     291.182945        1239
     Anza Vista                       267.932583        1239
     Bayview                          170.098665        1239
     Buena Vista Park                 347.394919        1239
     Central Richmond                 319.027623        1239
...                                          ...         ...
2016 Telegraph Hill                   903.049771        4390
     Twin Peaks                       970.085470        4390
     Van Ness/ Civic Center           552.602567        4390
     Visitacion Valley                328.319007        4390
     Westwood Park                    631.195426        4390

[397 rows x 2 columns]

In [46]:
# Use hvplot to create an interactive line plot of the average price per square foot
# The plot should have a dropdown selector for the neighborhood
prices_by_year_by_neighborhood.hvplot(groupby='neighborhood', x='year', rot=90
                                     )

:DynamicMap   [neighborhood]
   :NdOverlay   [Variable]
      :Curve   [year]   (value)

In [47]:
## Build an Interactive Neighborhood Map

In [76]:
# Load neighborhoods coordinates data
neighborhood_locations_df = pd.read_csv(Path('./Resources/neighborhoods_coordinates.csv'))

# Review the DataFrame
neighborhood_locations_df.set_index('Neighborhood')

                          Lat         Lon
Neighborhood
Alamo Square        37.791012 -122.402100
Anza Vista          37.779598 -122.443451
Bayview             37.734670 -122.401060
Bayview Heights     37.728740 -122.410980
Bernal Heights      37.728630 -122.443050
...                       ...         ...
West Portal         37.740260 -122.463880
Western Addition    37.792980 -122.435790
Westwood Highlands  37.734700 -122.456854
Westwood Park       37.734150 -122.457000
Yerba Buena         37.792980 -122.396360

[73 rows x 2 columns]

In [97]:
# Calculate the mean values for each neighborhood
all_neighborhood_info_df = sfo_data_df.groupby('neighborhood').mean()

# Review the resulting DataFrame
all_neighborhood_info_df

                    sale_price_sqr_foot  housing_units   gross_rent
neighborhood
Alamo Square                 366.020712      378401.00  2817.285714
Anza Vista                   373.382198      379050.00  3031.833333
Bayview                      204.588623      376454.00  2318.400000
Bayview Heights              590.792839      382295.00  3739.000000
Bernal Heights               576.746488      379374.50  3080.333333
...                                 ...            ...          ...
West Portal                  498.488485      376940.75  2515.500000
Western Addition             307.562201      377427.50  2555.166667
Westwood Highlands           533.703935      376454.00  2250.500000
Westwood Park                687.087575      382295.00  3959.000000
Yerba Buena                  576.709848      377427.50  2555.166667

[73 rows x 3 columns]

In [119]:

neighborhood_locations_df=neighborhood_locations_df.rename(columns={'Neighborhood':'neighborhood'})
neighborhood_locations_df=neighborhood_locations_df.set_index('neighborhood')

In [122]:
# Using the Pandas `concat` function, join the 
# neighborhood_locations_df and the all_neighborhood_info_df DataFrame
# The axis of the concatenation is "columns".
# The concat function will automatially combine columns with
# identical information, while keeping the additional columns.
all_neighborhoods_df = pd.concat(
    [neighborhood_locations_df, all_neighborhood_info_df], 
    axis="columns",
    sort=False,
)
all_neighborhoods_df=all_neighborhoods_df.dropna()
# Review the resulting DataFrame
all_neighborhoods_df

,Lat,Lon,sale_price_sqr_foot,housing_units,gross_rent
neighborhood,,,,,
Alamo Square,37.791012,-122.402100,366.020712,378401.00,2817.285714
Anza Vista,37.779598,-122.443451,373.382198,379050.00,3031.833333
Bayview,37.734670,-122.401060,204.588623,376454.00,2318.400000
Bayview Heights,37.728740,-122.410980,590.792839,382295.00,3739.000000
Buena Vista Park,37.768160,-122.439330,452.680591,378076.50,2698.833333
...,...,...,...,...,...
West Portal,37.740260,-122.463880,498.488485,376940.75,2515.500000
Western Addition,37.792980,-122.435790,307.562201,377427.50,2555.166667
Westwood Highlands,37.734700,-122.456854,533.703935,376454.00,2250.500000
Westwood Park,37.734150,-122.457000,687.087575,382295.00,3959.000000
Yerba Buena,37.792980,-122.396360,576.709848,377427.50,2555.166667

In [123]:
# Call the dropna function to remove any neighborhoods that do not have data
all_neighborhoods_df = all_neighborhoods_df.reset_index().dropna()

# Rename the "index" column as "Neighborhood" for use in the Visualization
all_neighborhoods_df = all_neighborhoods_df.rename(columns={"index": "Neighborhood"})

# Review the resulting DataFrame
display(all_neighborhoods_df.head())
display(all_neighborhoods_df.tail())

,neighborhood,Lat,Lon,sale_price_sqr_foot,housing_units,gross_rent
0,Alamo Square,37.791012,-122.402100,366.020712,378401.0,2817.285714
1,Anza Vista,37.779598,-122.443451,373.382198,379050.0,3031.833333
2,Bayview,37.734670,-122.401060,204.588623,376454.0,2318.400000
3,Bayview Heights,37.728740,-122.410980,590.792839,382295.0,3739.000000
4,Buena Vista Park,37.768160,-122.439330,452.680591,378076.5,2698.833333

,neighborhood,Lat,Lon,sale_price_sqr_foot,housing_units,gross_rent
64,West Portal,37.74026,-122.463880,498.488485,376940.75,2515.500000
65,Western Addition,37.79298,-122.435790,307.562201,377427.50,2555.166667
66,Westwood Highlands,37.73470,-122.456854,533.703935,376454.00,2250.500000
67,Westwood Park,37.73415,-122.457000,687.087575,382295.00,3959.000000
68,Yerba Buena,37.79298,-122.396360,576.709848,377427.50,2555.166667

In [125]:
# # Create a plot to analyze neighborhood info
# * Set the `geo` parameter to True.
# * Set the `size` parameter to “sale_price_sqr_foot”.
# * Set the `color` parameter to “gross_rent”.
# * Set the `frame_width` parameter to 700.
# * Set the `frame_height` parameter to 500.
# * Include a descriptive title.
# # YOUR CODE HERE

In [133]:
all_neighborhoods_df.hvplot.points(
    'Lon',
    'Lat',
    geo=True,
    size='sale_price_sqr_foot',
    color='gross_rent',
    tiles='OSM',
    frame_width=700,
    frame_height=500,
    title= 'Average by Neighborhood',
    scale=.5
    )

:Overlay
   .Tiles.I  :Tiles   [x,y]
   .Points.I :Points   [Lon,Lat]   (gross_rent,sale_price_sqr_foot)